name: build

on: [push, pull_request]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Java 8
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Build
      run: sudo bash ./gradlew assembleRelease
    - name: Artifact
      uses: actions/upload-artifact@v2
      with:
        name: unsigned-apk
        path: app/build/outputs/apk
